 -- Getting all CONTRIBUTORS for a MODEL:

SELECT s.CONTRIBUTOR_ID, FIRST_NAME, LAST_NAME
FROM MODELS_CONTRIBUTORS sc 
INNER JOIN CONTRIBUTORS s ON s.CONTRIBUTOR_ID = sc.CONTRIBUTOR_ID
WHERE sc.MODEL_ID = 1;
  
 -- Getting all MODELS for a CONTRIBUTORS: 

SELECT c.MODEL_ID, MODEL_NAME
FROM MODELS_CONTRIBUTORS sc 
INNER JOIN MODELS c ON c.MODEL_ID = sc.MODEL_ID
WHERE sc.CONTRIBUTOR_ID = 1;

-- Getting the relationships of models

SELECT E.name AS "CHILD", M.name AS "PARENT"
FROM MODELS_SEGMENTATION E LEFT OUTER JOIN 
  (MODELS_SEGMENTATION S INNER JOIN MODELS_SEGMENTATION M 
	ON S.PARENT_ID = M.ID)
  ON E.ID = S.ID
ORDER BY E.NAME


DECLARE
BEGIN
 add_admin_to_activity(6,2);
END;

DECLARE
BEGIN
 remove_admin_from_activity(6,2);
END;

DECLARE
BEGIN
 checkout_activity(11,1);
END;

DECLARE
BEGIN
 display_admins_in_act(6);
END;